[project]
name = "http-status-code-constraints"
version = "0.1.0"
description = "Constraining LLMs to generate valid HTTP status codes using FSMs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.4.0",
    "python-dotenv>=1.0.0",
]
