[project]
name = "latex-math-fsm-constraints"
version = "0.3.0"
description = "Constraining LLMs to generate valid LaTeX mathematical expressions using FSMs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.4.0",
    "python-dotenv>=1.0.0",
]
