[project]
name = "contraining-llms-with-fsms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-community>=0.3.29",
    "langchain-groq>=0.3.7",
]
